contentSecurityPolicy:
  default-src: "'self'"
  script-src: "'self' 'unsafe-inline' https://unpkg.com"
  style-src: "'self' 'unsafe-inline'"
  img-src: "'self' data:"
  font-src: "'self' https://fonts.gstatic.com data:"
  connect-src: "'self' https://identity.netlify.com https://api.netlify.com"
